services:
  postgres:
    image: postgres:16-alpine
    container_name: contbet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: contbet
      POSTGRES_PASSWORD: contbet_dev
      POSTGRES_DB: contbet
    ports:
      - "5432:5432"
    volumes:
      - contbet_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contbet"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: node:20
    container_name: contbet-api
    restart: unless-stopped
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3001
      JWT_SECRET: troque-este-segredo-em-producao-use-um-valor-longo-e-aleatorio
      JWT_EXPIRES_IN: 7d
      FISCAL_ENCRYPTION_KEY: 047ce25a59cf22c4b9c30142a7c864563477847078930b7604a05241cb1c0972
      CORS_ORIGIN: http://localhost:3000
      DATABASE_URL: postgresql://contbet:contbet_dev@postgres:5432/contbet?schema=public
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 500
    command: sh -c "npm install && npx prisma generate && npm run start:dev"
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/app
      - contbet_api_node_modules:/app/node_modules

  web:
    image: node:20-alpine
    container_name: contbet-web
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - api
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - contbet_web_node_modules:/app/node_modules

volumes:
  contbet_pg_data:
  contbet_api_node_modules:
  contbet_web_node_modules:
